"""Add file_name field to Order model

Revision ID: 27461841c03e
Revises: 
Create Date: 2024-12-18 19:38:34.496338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27461841c03e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###
