"""Add assigned_employee to Order

Revision ID: 933dadc304a1
Revises: 27461841c03e
Create Date: 2025-01-08 18:27:28.810486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933dadc304a1'
down_revision = '27461841c03e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_employee', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('assigned_employee')

    op.create_table('employee',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('position', sa.VARCHAR(length=100), nullable=False),
    sa.Column('department', sa.VARCHAR(length=100), nullable=False),
    sa.Column('photo', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
